#!/bin/bash
#startx replacement file
#@linux.org.ru

WM=/usr/bin/ratpoison

LANG=en_US.UTF-8
export LANG

/usr/bin/setxkbmap -option "ctrl:nocaps"
[[ -f ~/.Xresources ]] && xrdb -merge -I$HOME ~/.Xresources

env XSECURELOCK_SAVER=saver_xscreensaver

xss-lock -- env XSECURELOCK_AUTH_FOREGROUND_COLOR="#00cc00" XSECURELOCK_BACKGROUND_COLOR="#000000" XSECURELOCK_PASSWORD_PROMPT="time_hex" XSECURELOCK_SHOW_DATETIME="true" XSECURELOCK_SHOW_HOSTNAME="true" XSECURELOCK_FONT="-*-terminus-medium-r-normal-*-17-*-*-*-*-*-*-*" XSECURELOCK_SHOW_USERNAME="true" XSECURELOCK_SAVER=saver_xscreensaver xsecurelock &

xset s on
xset s 128 120

xbindkeys
xsetroot -cursor_name left_ptr

$WM
